# feedback.py — SQLAlchemy model for the `feedback` table
# One feedback row per answer — generated by CoachNode in parallel with EvaluatorNode.
# Stores communication quality separately from technical quality (Score table).
# Session-level summaries are computed by querying this table — not stored redundantly.

import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, Integer, String, Text, JSON, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models import Base


class Feedback(Base):
    __tablename__ = "feedback"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    # unique=True — one feedback per answer, enforced at DB level
    answer_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("answers.id"), nullable=False, index=True, unique=True
    )

    # ── Regex-computed (no API cost) ──────────────────────────────
    filler_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)   # Total filler words found
    word_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)     # Total words in transcript

    # ── LLM-assessed ─────────────────────────────────────────────
    clarity_score: Mapped[int] = mapped_column(Integer, nullable=False)             # 1-10: organization + structure
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False)          # 1-10: assertiveness, no hedging
    pace_assessment: Mapped[str] = mapped_column(String(30), nullable=False)        # too_slow | appropriate | too_fast

    # JSON array of strings — specific actionable tips (e.g. "Reduce 'basically' — used 4 times")
    recommendations: Mapped[list] = mapped_column(JSON, nullable=False, default=list)

    overall_communication_score: Mapped[int] = mapped_column(Integer, nullable=False)  # 1-10 holistic

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<Feedback answer={self.answer_id[:8]} comm={self.overall_communication_score}/10 fillers={self.filler_count}>"
    