# score.py — SQLAlchemy model for the `scores` table
# One score row per answer — generated by EvaluatorNode after each candidate response.
# Scores are 1–10 integers. reasoning explains WHY those scores were given.

import uuid
from datetime import datetime

from sqlalchemy import Boolean, ForeignKey, Integer, String, Text, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models import Base


class Score(Base):
    __tablename__ = "scores"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    # One score per answer — index for fast lookup when building session history
    answer_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("answers.id"), nullable=False, index=True, unique=True
    )

    # Dimension scores — each 1-10
    technical_score: Mapped[int] = mapped_column(Integer, nullable=False)   # Depth of technical knowledge
    structure_score: Mapped[int] = mapped_column(Integer, nullable=False)   # Clarity, examples, STAR method
    relevance_score: Mapped[int] = mapped_column(Integer, nullable=False)   # How directly question was answered

    # Overall — LLM's holistic assessment, not a simple average
    overall_score: Mapped[int] = mapped_column(Integer, nullable=False)

    # LLM's explanation — stored so user can read why they got that score
    reasoning: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # If True: InterviewerNode should probe same topic instead of moving on
    follow_up_needed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<Score answer={self.answer_id[:8]} overall={self.overall_score}/10>"
    